apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

resources:
  - pod-config.yaml
  - ../postgres-operator
  # - ../postgres-operator-ui

patchesStrategicMerge:
  - configmap.yaml