apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAzLdPNstnrauXP1QHhfpabsdbcrInD/EwiaZSjGsuvSMcClOLKH4+rb0Gx9q+CerWHfNvT9fuWfDe02SNFObGGeN6deYTNXUoMBuqgWIJB2MH6rUiR9rNOt6r6hsCp7+Y8L7ZMJAv+EHMp7cc3cPAN8nth2j1duK0tXZuqV3/aC/mK1If96VZAtQ7LoQz4eVkv2g/6nIgGpe70IHKIwsY2zFvYloMidws1hIdR9XjeOmxrkbXkwhMSaQczAoxREnytZcIbhILgD5VMP/+R4b3+E0my0VaGsi/ZN+TzOa0/3miXHhblVJ05Z01jH+6H+sqEMEksCtz6dMZUpp6yesbgYrBkcGRHaPXnjzzHrKLXk6VWTJtzNS2OAIwHMQb06PmZ3hnSVPU4w1JRxf3rtw2z9SG1LgYk8dLUW4S+s47UJtdMApZ6W+Wn9Dc6SZ0iwcAqCTejoeFiMYVqq1yJnS911tj3HcFo719wMFSc3pUu9ugvx8pNyz1OcvtLIpITUKLkv+Ja73ZH3LugCXLph1GOjaYWRNokwbz1oYTWdjUxzmWiXGIQSgmmpAJGS2QDQqojClmrpWz3tX1GYY94Ew91F0nJ9B7+QQwrYYfwi8XELpS1D92pErAYlxCwrX9p87COQNUKcpOqw8Bp2wl5HDB7oGs72Xd6occXW+cHTXedLrJYgX5L0SaGjoHWtamrRDWY8npxCBKEMRRVwF+VqNi7W31s3UP3TCn+0CPHuBZ6TwF1+cX0s0XXHxnvN0MQRBKBAm0=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque

