apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBF/3FzamzP6TnPfVRelRlPPVIDRN/srMS71JzY/V7wLHuUxkZ4Z6q0vhsqYlRFW9kFotP9iI7l0DYGBYh/XIXbFDBzB050yIs7oFI+UedsBVYdmPq/6JFcxh61DC9UMSJYd+Rqfb0eZbJkNkTGjF7CUYcN1/CVp5k5ADtMvjTPnXqpAXLS96Qu+9L1PW/UFOYMFh7pbKpMtvhfBiUEr4c5lY6OSZGykWkXtJuldY27akW5iVt81slObeS5kg3GylnROWkgZNEXjYHTZjLTwsgHtw397hEzxGDAuFletPj7Pqj3+ad1wR/m0wpjQ+x3dEN3D94SoZqc+6ANH4ALkL46pwe3JgABl1izZaB7RQqF/26Ha8+gFd7YxiE3jqhrrcfWMS7uVcxTV1AvBIqAXCuIvaimdsOG3bUX/JXvQ6DJ151Dipe0mezgUYDA8fdggs2JDxp5jLFie3gOzOqtrd2buW2KabTdhqPYhLozj3M1p03h/hT/AgiFKh/+03/YXaVPJTmaJ5Qhv37ZlepLpTdHcVhIk2fCe0UggZ0E8lxCH3+6Lv8SJ+8TvaQl2eydTo9IAfEeUyafmYf9EqcSdiQya1yfu3zAn6Qb9aqA6GdDnB7L2MGoKoXq4T3kCFNNf5xtilYxkU/7jrb27cxq6QqMb6dGfWyTfLuYdMEM9+HXDNdWYRpkUZhioRqjQqBHGSAJ6bDe/1TTaVhyNZ3ZYY1GfhNJIKJAd9QaxH+yLrSS79EDf2pkHONB9fPM3tlR2vQ+vTw=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque

