apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apiservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/[username]/samplegitopsapp.git'
    path: structure/extention-apps/apiservice
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apiservice
  syncPolicy:
    automated:
      selfHeal: true
      prune: true