apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gruzchik/argocd-sandbox.git'
    path: structure/httpd
    targetRevision: main
    helm:
      releaseName: httpd
      values: |
        replicaCount: 2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true