apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gruzchik/argocd-sandbox.git'
    path: structure/helm-charts/cloudnative-pg
    targetRevision: main
    helm:
      releaseName: cloudnative
      values: |
        replicaCount: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true