apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepageserver-secondary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gruzchik/argocd-sandbox.git'
    path: onepageserver
    targetRevision: main
  destination:
    server: 'https://192.168.0.153:6443'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true